import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomBytes } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
const argon2 = createRequire(new URL('../server/package.json', import.meta.url))('argon2');
import { HASH_OPTIONS } from '../server/src/app.js';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dir = path.join(root, '.secrets');
if (fs.existsSync(dir)) throw new Error('.secrets already exists; use documented rotation, not setup again');
fs.mkdirSync(dir, { mode: 0o700 });
if (process.platform === 'win32') execFileSync('powershell.exe', ['-NoProfile','-ExecutionPolicy','Bypass','-File',path.join(root,'deployment/protect-secrets.ps1')], {windowsHide:true});
const write = (name, value) => fs.writeFileSync(path.join(dir, name), value, { mode: 0o600 });
const secret = () => randomBytes(32).toString('hex');
const admin = secret(), app = secret();
write('db-admin-password', admin); write('db-app-password', app); write('session-secret', secret());
write('backup-key', randomBytes(32));
const users = [{ username: 'alice', password: secret() }, { username: 'bob', password: secret() }];
write('demo-users.json', JSON.stringify(users, null, 2));
let sql = `CREATE ROLE birthday_app LOGIN PASSWORD '${app}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;\n`;
sql += fs.readFileSync(path.join(root, 'deployment/schema.sql'), 'utf8');
for (const u of users) sql += `\nINSERT INTO users(username,password_hash) VALUES('${u.username}','${await argon2.hash(u.password, HASH_OPTIONS)}');`;
write('init.sql', sql);
const openssl = process.env.OPENSSL || 'openssl';
const run = args => execFileSync(openssl, args, { cwd: dir, stdio: 'pipe' });
run(['req','-x509','-newkey','rsa:3072','-sha256','-nodes','-keyout','ca.key','-out','ca.crt','-days','365','-subj','/CN=Candlelight local lab CA']);
run(['req','-newkey','rsa:3072','-nodes','-keyout','server.key','-out','server.csr','-subj','/CN=postgres']);
write('server.ext', 'subjectAltName=DNS:postgres\nkeyUsage=digitalSignature,keyEncipherment\nextendedKeyUsage=serverAuth\n');
run(['x509','-req','-in','server.csr','-CA','ca.crt','-CAkey','ca.key','-CAcreateserial','-out','server.crt','-days','90','-sha256','-extfile','server.ext']);
for (const name of fs.readdirSync(dir)) fs.chmodSync(path.join(dir, name), 0o600);
console.log('Generated unique local credentials and TLS certificates. Demo logins are in .secrets/demo-users.json; do not commit or share them.');
